# Generated by Django 3.1.6 on 2021-02-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ASD',
            new_name='SOCIAL_NETWORK',
        ),
    ]
