# Generated by Django 3.1.6 on 2021-02-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20210211_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_count', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('name', models.CharField(choices=[('TELEGRAM', 'TELEGRAM'), ('TIKTOK', 'TIKTOK'), ('INSTAGRAM', 'INSTAGRAM'), ('YOUTUBE', 'YOUTUBE')], max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='SOCIAL_NETWORK',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.category'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
    ]
